version: "3"

services:
  api-nlw-space-mariadb:
    container_name: api-nlw-space-mariadb
    image: bitnami/mariadb:latest
    ports:
      - 3307:3306 # first is host port, second is container port
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=mysql
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=apiNlwSpace

  api-nlw-space-mariadb-shadow:
    container_name: api-nlw-space-mariadb-shadow
    image: bitnami/mariadb:latest
    ports:
      - 3308:3306 # first is host port, second is container port
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=mysql
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=apiNlwSpaceShadow
